// Generated from the approved Clario icon inventory. Keep entries deduplicated by English keyword.
export type ProceduralIconEntry = { group: string; key: string; label: string; keywords: string; template: string };

export const PROCEDURAL_ICON_GROUPS = [{"id": "education", "label": "Éducation et école"}, {"id": "documents", "label": "Documents et bureau"}, {"id": "business", "label": "Affaires et finance"}, {"id": "math", "label": "Mathématiques"}, {"id": "science", "label": "Sciences"}, {"id": "technology", "label": "Technologie et informatique"}, {"id": "everyday", "label": "Objets du quotidien"}, {"id": "diagrams", "label": "Flèches et schémas"}, {"id": "emphasis", "label": "Mise en évidence"}, {"id": "charts", "label": "Graphiques et données"}, {"id": "emotions", "label": "Émotions et réactions"}, {"id": "concepts", "label": "Symboles universels"}] as const;

export const PROCEDURAL_ICON_CATALOG: ProceduralIconEntry[] = [
  { group: 'education', key: 'book', label: 'Livre', keywords: 'Book', template: 'book' },
  { group: 'education', key: 'open-book', label: 'Livre ouvert', keywords: 'Open book', template: 'book' },
  { group: 'education', key: 'notebook', label: 'Cahier', keywords: 'Notebook', template: 'book' },
  { group: 'education', key: 'textbook', label: 'Manuel scolaire', keywords: 'Textbook', template: 'book' },
  { group: 'education', key: 'worksheet', label: 'Feuille d’exercices', keywords: 'Worksheet', template: 'document' },
  { group: 'education', key: 'flashcards', label: 'Cartes mémoire', keywords: 'Flashcards', template: 'document' },
  { group: 'education', key: 'pencil', label: 'Crayon', keywords: 'Pencil', template: 'writing' },
  { group: 'education', key: 'pen', label: 'Stylo', keywords: 'Pen', template: 'writing' },
  { group: 'education', key: 'eraser', label: 'Gomme', keywords: 'Eraser', template: 'writing' },
  { group: 'education', key: 'ruler', label: 'Règle', keywords: 'Ruler', template: 'writing' },
  { group: 'education', key: 'highlighter', label: 'Surligneur', keywords: 'Highlighter', template: 'writing' },
  { group: 'education', key: 'marker', label: 'Marqueur', keywords: 'Marker', template: 'writing' },
  { group: 'education', key: 'backpack', label: 'Sac à dos', keywords: 'Backpack', template: 'education' },
  { group: 'education', key: 'desk', label: 'Bureau', keywords: 'Desk', template: 'building' },
  { group: 'education', key: 'chair', label: 'Chaise', keywords: 'Chair', template: 'building' },
  { group: 'education', key: 'blackboard', label: 'Tableau noir', keywords: 'Blackboard', template: 'building' },
  { group: 'education', key: 'whiteboard', label: 'Tableau blanc', keywords: 'Whiteboard', template: 'building' },
  { group: 'education', key: 'classroom', label: 'Salle de classe', keywords: 'Classroom', template: 'building' },
  { group: 'education', key: 'school', label: 'École', keywords: 'School', template: 'building' },
  { group: 'education', key: 'graduation-cap', label: 'Mortier de diplômé', keywords: 'Graduation cap', template: 'education' },
  { group: 'education', key: 'diploma', label: 'Diplôme', keywords: 'Diploma', template: 'document' },
  { group: 'education', key: 'certificate', label: 'Certificat', keywords: 'Certificate', template: 'document' },
  { group: 'education', key: 'clipboard', label: 'Presse-papiers', keywords: 'Clipboard', template: 'building' },
  { group: 'education', key: 'folder', label: 'Dossier', keywords: 'Folder', template: 'education' },
  { group: 'education', key: 'binder', label: 'Classeur', keywords: 'Binder', template: 'book' },
  { group: 'education', key: 'stack-of-papers', label: 'Pile de feuilles', keywords: 'Stack of papers', template: 'document' },
  { group: 'education', key: 'homework', label: 'Devoirs', keywords: 'Homework', template: 'document' },
  { group: 'education', key: 'assignment', label: 'Travail à remettre', keywords: 'Assignment', template: 'document' },
  { group: 'education', key: 'exam-paper', label: 'Copie d’examen', keywords: 'Exam paper', template: 'document' },
  { group: 'education', key: 'quiz-paper', label: 'Feuille de quiz', keywords: 'Quiz paper', template: 'document' },
  { group: 'education', key: 'question-mark', label: 'Point d’interrogation', keywords: 'Question mark', template: 'diagram' },
  { group: 'education', key: 'answer-sheet', label: 'Feuille de réponses', keywords: 'Answer sheet', template: 'diagram' },
  { group: 'education', key: 'correct-answer', label: 'Bonne réponse', keywords: 'Correct answer', template: 'diagram' },
  { group: 'education', key: 'incorrect-answer', label: 'Mauvaise réponse', keywords: 'Incorrect answer', template: 'diagram' },
  { group: 'education', key: 'lightbulb', label: 'Ampoule', keywords: 'Lightbulb', template: 'education' },
  { group: 'education', key: 'brain', label: 'Cerveau', keywords: 'Brain', template: 'body' },
  { group: 'education', key: 'magnifying-glass', label: 'Loupe', keywords: 'Magnifying glass', template: 'education' },
  { group: 'education', key: 'calculator', label: 'Calculatrice', keywords: 'Calculator', template: 'education' },
  { group: 'education', key: 'clock', label: 'Horloge', keywords: 'Clock', template: 'concept' },
  { group: 'education', key: 'calendar', label: 'Calendrier', keywords: 'Calendar', template: 'education' },
  { group: 'education', key: 'study-timer', label: 'Minuteur d’étude', keywords: 'Study timer', template: 'education' },
  { group: 'education', key: 'trophy', label: 'Trophée', keywords: 'Trophy', template: 'science' },
  { group: 'education', key: 'medal', label: 'Médaille', keywords: 'Medal', template: 'badge' },
  { group: 'education', key: 'star', label: 'Étoile', keywords: 'Star', template: 'badge' },
  { group: 'education', key: 'target', label: 'Cible', keywords: 'Target', template: 'badge' },
  { group: 'education', key: 'progress-arrow', label: 'Flèche de progression', keywords: 'Progress arrow', template: 'arrow' },
  { group: 'education', key: 'knowledge-tree', label: 'Arbre des connaissances', keywords: 'Knowledge tree', template: 'nature' },
  { group: 'education', key: 'thought-bubble', label: 'Bulle de pensée', keywords: 'Thought bubble', template: 'callout' },
  { group: 'documents', key: 'invoice', label: 'Facture', keywords: 'Invoice', template: 'document' },
  { group: 'documents', key: 'receipt', label: 'Reçu', keywords: 'Receipt', template: 'document' },
  { group: 'documents', key: 'purchase-order', label: 'Bon de commande', keywords: 'Purchase order', template: 'document' },
  { group: 'documents', key: 'sales-order', label: 'Commande client', keywords: 'Sales order', template: 'document' },
  { group: 'documents', key: 'contract', label: 'Contrat', keywords: 'Contract', template: 'document' },
  { group: 'documents', key: 'report', label: 'Rapport', keywords: 'Report', template: 'document' },
  { group: 'documents', key: 'financial-statement', label: 'États financiers', keywords: 'Financial statement', template: 'document' },
  { group: 'documents', key: 'balance-sheet', label: 'Bilan', keywords: 'Balance sheet', template: 'documents' },
  { group: 'documents', key: 'income-statement', label: 'État des résultats', keywords: 'Income statement', template: 'document' },
  { group: 'documents', key: 'cash-flow-statement', label: 'État des flux de trésorerie', keywords: 'Cash-flow statement', template: 'document' },
  { group: 'documents', key: 'bank-statement', label: 'Relevé bancaire', keywords: 'Bank statement', template: 'document' },
  { group: 'documents', key: 'tax-form', label: 'Formulaire fiscal', keywords: 'Tax form', template: 'document' },
  { group: 'documents', key: 'payslip', label: 'Fiche de paie', keywords: 'Payslip', template: 'document' },
  { group: 'documents', key: 'timesheet', label: 'Feuille de temps', keywords: 'Timesheet', template: 'document' },
  { group: 'documents', key: 'expense-report', label: 'Note de frais', keywords: 'Expense report', template: 'document' },
  { group: 'documents', key: 'budget', label: 'Budget', keywords: 'Budget', template: 'document' },
  { group: 'documents', key: 'spreadsheet', label: 'Feuille de calcul', keywords: 'Spreadsheet', template: 'documents' },
  { group: 'documents', key: 'table', label: 'Tableau', keywords: 'Table', template: 'documents' },
  { group: 'documents', key: 'chart', label: 'Graphique', keywords: 'Chart', template: 'chart' },
  { group: 'documents', key: 'graph', label: 'Courbe', keywords: 'Graph', template: 'science' },
  { group: 'documents', key: 'letter', label: 'Lettre', keywords: 'Letter', template: 'document' },
  { group: 'documents', key: 'email', label: 'Courriel', keywords: 'Email', template: 'tech' },
  { group: 'documents', key: 'envelope', label: 'Enveloppe', keywords: 'Envelope', template: 'documents' },
  { group: 'documents', key: 'file', label: 'Fichier', keywords: 'File', template: 'document' },
  { group: 'documents', key: 'archive-box', label: 'Boîte d’archives', keywords: 'Archive box', template: 'badge' },
  { group: 'documents', key: 'stamp', label: 'Tampon', keywords: 'Stamp', template: 'documents' },
  { group: 'documents', key: 'signature', label: 'Signature', keywords: 'Signature', template: 'writing' },
  { group: 'documents', key: 'checklist', label: 'Liste de vérification', keywords: 'Checklist', template: 'document' },
  { group: 'documents', key: 'form', label: 'Formulaire', keywords: 'Form', template: 'document' },
  { group: 'documents', key: 'id-card', label: 'Carte d’identité', keywords: 'ID card', template: 'vehicle' },
  { group: 'documents', key: 'agenda', label: 'Agenda', keywords: 'Agenda', template: 'document' },
  { group: 'documents', key: 'presentation', label: 'Présentation', keywords: 'Presentation', template: 'documents' },
  { group: 'documents', key: 'laptop', label: 'Ordinateur portable', keywords: 'Laptop', template: 'device' },
  { group: 'documents', key: 'desktop-computer', label: 'Ordinateur de bureau', keywords: 'Desktop computer', template: 'device' },
  { group: 'documents', key: 'monitor', label: 'Écran', keywords: 'Monitor', template: 'device' },
  { group: 'documents', key: 'printer', label: 'Imprimante', keywords: 'Printer', template: 'device' },
  { group: 'documents', key: 'scanner', label: 'Numériseur', keywords: 'Scanner', template: 'device' },
  { group: 'documents', key: 'phone', label: 'Téléphone', keywords: 'Phone', template: 'device' },
  { group: 'documents', key: 'cloud-document', label: 'Document infonuagique', keywords: 'Cloud document', template: 'document' },
  { group: 'documents', key: 'database', label: 'Base de données', keywords: 'Database', template: 'tech' },
  { group: 'documents', key: 'pdf', label: 'Document PDF', keywords: 'PDF', template: 'document' },
  { group: 'business', key: 'coin', label: 'Pièce de monnaie', keywords: 'Coin', template: 'money' },
  { group: 'business', key: 'coins-stack', label: 'Pile de pièces', keywords: 'Coins stack', template: 'money' },
  { group: 'business', key: 'banknote', label: 'Billet', keywords: 'Banknote', template: 'money' },
  { group: 'business', key: 'money-stack', label: 'Pile d’argent', keywords: 'Money stack', template: 'money' },
  { group: 'business', key: 'wallet', label: 'Portefeuille', keywords: 'Wallet', template: 'money' },
  { group: 'business', key: 'cash-register', label: 'Caisse enregistreuse', keywords: 'Cash register', template: 'money' },
  { group: 'business', key: 'piggy-bank', label: 'Tirelire', keywords: 'Piggy bank', template: 'money' },
  { group: 'business', key: 'bank', label: 'Banque', keywords: 'Bank', template: 'money' },
  { group: 'business', key: 'atm', label: 'Guichet automatique', keywords: 'ATM', template: 'business' },
  { group: 'business', key: 'credit-card', label: 'Carte de crédit', keywords: 'Credit card', template: 'money' },
  { group: 'business', key: 'debit-card', label: 'Carte de débit', keywords: 'Debit card', template: 'money' },
  { group: 'business', key: 'payment-terminal', label: 'Terminal de paiement', keywords: 'Payment terminal', template: 'device' },
  { group: 'business', key: 'money-transfer', label: 'Transfert d’argent', keywords: 'Money transfer', template: 'money' },
  { group: 'business', key: 'company-building', label: 'Immeuble d’entreprise', keywords: 'Company building', template: 'building' },
  { group: 'business', key: 'store', label: 'Magasin', keywords: 'Store', template: 'building' },
  { group: 'business', key: 'factory', label: 'Usine', keywords: 'Factory', template: 'building' },
  { group: 'business', key: 'warehouse', label: 'Entrepôt', keywords: 'Warehouse', template: 'building' },
  { group: 'business', key: 'office', label: 'Bureau de travail', keywords: 'Office', template: 'building' },
  { group: 'business', key: 'team', label: 'Équipe', keywords: 'Team', template: 'person' },
  { group: 'business', key: 'meeting', label: 'Réunion', keywords: 'Meeting', template: 'person' },
  { group: 'business', key: 'customer', label: 'Client·e', keywords: 'Customer', template: 'person' },
  { group: 'business', key: 'supplier', label: 'Fournisseur', keywords: 'Supplier', template: 'person' },
  { group: 'business', key: 'employee', label: 'Employé·e', keywords: 'Employee', template: 'person' },
  { group: 'business', key: 'manager', label: 'Gestionnaire', keywords: 'Manager', template: 'person' },
  { group: 'business', key: 'investor', label: 'Investisseur', keywords: 'Investor', template: 'money' },
  { group: 'business', key: 'partnership', label: 'Partenariat', keywords: 'Partnership', template: 'person' },
  { group: 'business', key: 'sale', label: 'Vente', keywords: 'Sale', template: 'money' },
  { group: 'business', key: 'purchase', label: 'Achat', keywords: 'Purchase', template: 'money' },
  { group: 'business', key: 'inventory', label: 'Inventaire', keywords: 'Inventory', template: 'business' },
  { group: 'business', key: 'shipment', label: 'Expédition', keywords: 'Shipment', template: 'vehicle' },
  { group: 'business', key: 'delivery-truck', label: 'Camion de livraison', keywords: 'Delivery truck', template: 'vehicle' },
  { group: 'business', key: 'debit', label: 'Débit', keywords: 'Debit', template: 'money' },
  { group: 'business', key: 'credit', label: 'Crédit', keywords: 'Credit', template: 'money' },
  { group: 'business', key: 'ledger', label: 'Grand livre', keywords: 'Ledger', template: 'business' },
  { group: 'business', key: 'journal', label: 'Journal comptable', keywords: 'Journal', template: 'business' },
  { group: 'business', key: 't-account', label: 'Compte en T', keywords: 'T-account', template: 'business' },
  { group: 'business', key: 'trial-balance', label: 'Balance de vérification', keywords: 'Trial balance', template: 'business' },
  { group: 'business', key: 'revenue', label: 'Revenu', keywords: 'Revenue', template: 'money' },
  { group: 'business', key: 'expense', label: 'Dépense', keywords: 'Expense', template: 'writing' },
  { group: 'business', key: 'profit', label: 'Profit', keywords: 'Profit', template: 'money' },
  { group: 'business', key: 'loss', label: 'Perte', keywords: 'Loss', template: 'money' },
  { group: 'business', key: 'asset', label: 'Actif', keywords: 'Asset', template: 'money' },
  { group: 'business', key: 'liability', label: 'Passif', keywords: 'Liability', template: 'money' },
  { group: 'business', key: 'equity', label: 'Capitaux propres', keywords: 'Equity', template: 'money' },
  { group: 'business', key: 'depreciation', label: 'Amortissement', keywords: 'Depreciation', template: 'business' },
  { group: 'business', key: 'tax', label: 'Impôt', keywords: 'Tax', template: 'money' },
  { group: 'business', key: 'gst-hst-qst', label: 'TPS / TVH / TVQ', keywords: 'GST/HST/QST', template: 'business' },
  { group: 'business', key: 'bank-reconciliation', label: 'Rapprochement bancaire', keywords: 'Bank reconciliation', template: 'money' },
  { group: 'business', key: 'accounts-receivable', label: 'Comptes clients', keywords: 'Accounts receivable', template: 'business' },
  { group: 'business', key: 'accounts-payable', label: 'Comptes fournisseurs', keywords: 'Accounts payable', template: 'business' },
  { group: 'business', key: 'payroll', label: 'Paie', keywords: 'Payroll', template: 'money' },
  { group: 'business', key: 'cost', label: 'Coût', keywords: 'Cost', template: 'money' },
  { group: 'business', key: 'forecast', label: 'Prévision', keywords: 'Forecast', template: 'business' },
  { group: 'business', key: 'break-even', label: 'Seuil de rentabilité', keywords: 'Break-even', template: 'business' },
  { group: 'business', key: 'cash-flow', label: 'Flux de trésorerie', keywords: 'Cash flow', template: 'money' },
  { group: 'business', key: 'audit', label: 'Audit', keywords: 'Audit', template: 'money' },
  { group: 'business', key: 'financial-analysis', label: 'Analyse financière', keywords: 'Financial analysis', template: 'money' },
  { group: 'math', key: 'addition', label: 'Addition', keywords: 'Addition', template: 'math' },
  { group: 'math', key: 'subtraction', label: 'Soustraction', keywords: 'Subtraction', template: 'math' },
  { group: 'math', key: 'multiplication', label: 'Multiplication', keywords: 'Multiplication', template: 'math' },
  { group: 'math', key: 'division', label: 'Division', keywords: 'Division', template: 'math' },
  { group: 'math', key: 'equal-sign', label: 'Signe égal', keywords: 'Equal sign', template: 'math' },
  { group: 'math', key: 'greater-than', label: 'Supérieur à', keywords: 'Greater than', template: 'math' },
  { group: 'math', key: 'less-than', label: 'Inférieur à', keywords: 'Less than', template: 'math' },
  { group: 'math', key: 'percentage', label: 'Pourcentage', keywords: 'Percentage', template: 'math' },
  { group: 'math', key: 'fraction', label: 'Fraction', keywords: 'Fraction', template: 'math' },
  { group: 'math', key: 'decimal', label: 'Nombre décimal', keywords: 'Decimal', template: 'math' },
  { group: 'math', key: 'ratio', label: 'Ratio', keywords: 'Ratio', template: 'math' },
  { group: 'math', key: 'proportion', label: 'Proportion', keywords: 'Proportion', template: 'math' },
  { group: 'math', key: 'number-line', label: 'Droite numérique', keywords: 'Number line', template: 'shape' },
  { group: 'math', key: 'negative-numbers', label: 'Nombres négatifs', keywords: 'Negative numbers', template: 'math' },
  { group: 'math', key: 'positive-numbers', label: 'Nombres positifs', keywords: 'Positive numbers', template: 'math' },
  { group: 'math', key: 'variable', label: 'Variable', keywords: 'Variable', template: 'math' },
  { group: 'math', key: 'equation', label: 'Équation', keywords: 'Equation', template: 'math' },
  { group: 'math', key: 'inequality', label: 'Inéquation', keywords: 'Inequality', template: 'math' },
  { group: 'math', key: 'function', label: 'Fonction', keywords: 'Function', template: 'math' },
  { group: 'math', key: 'formula', label: 'Formule', keywords: 'Formula', template: 'document' },
  { group: 'math', key: 'unknown', label: 'Inconnue', keywords: 'Unknown', template: 'math' },
  { group: 'math', key: 'system-of-equations', label: 'Système d’équations', keywords: 'System of equations', template: 'math' },
  { group: 'math', key: 'coordinate-plane', label: 'Plan cartésien', keywords: 'Coordinate plane', template: 'shape' },
  { group: 'math', key: 'x-axis', label: 'Axe X', keywords: 'X-axis', template: 'shape' },
  { group: 'math', key: 'y-axis', label: 'Axe Y', keywords: 'Y-axis', template: 'shape' },
  { group: 'math', key: 'parabola', label: 'Parabole', keywords: 'Parabola', template: 'shape' },
  { group: 'math', key: 'linear-equation', label: 'Équation linéaire', keywords: 'Linear equation', template: 'math' },
  { group: 'math', key: 'slope', label: 'Pente', keywords: 'Slope', template: 'shape' },
  { group: 'math', key: 'intercept', label: 'Ordonnée à l’origine', keywords: 'Intercept', template: 'shape' },
  { group: 'math', key: 'triangle', label: 'Triangle', keywords: 'Triangle', template: 'shape' },
  { group: 'math', key: 'square', label: 'Carré', keywords: 'Square', template: 'shape' },
  { group: 'math', key: 'rectangle', label: 'Rectangle', keywords: 'Rectangle', template: 'shape' },
  { group: 'math', key: 'circle', label: 'Cercle', keywords: 'Circle', template: 'shape' },
  { group: 'math', key: 'pentagon', label: 'Pentagone', keywords: 'Pentagon', template: 'writing' },
  { group: 'math', key: 'hexagon', label: 'Hexagone', keywords: 'Hexagon', template: 'shape' },
  { group: 'math', key: 'cube', label: 'Cube', keywords: 'Cube', template: 'shape' },
  { group: 'math', key: 'cylinder', label: 'Cylindre', keywords: 'Cylinder', template: 'shape' },
  { group: 'math', key: 'sphere', label: 'Sphère', keywords: 'Sphere', template: 'shape' },
  { group: 'math', key: 'cone', label: 'Cône', keywords: 'Cone', template: 'shape' },
  { group: 'math', key: 'angle', label: 'Angle', keywords: 'Angle', template: 'shape' },
  { group: 'math', key: 'protractor', label: 'Rapporteur', keywords: 'Protractor', template: 'math' },
  { group: 'math', key: 'derivative', label: 'Dérivée', keywords: 'Derivative', template: 'math' },
  { group: 'math', key: 'integral', label: 'Intégrale', keywords: 'Integral', template: 'math' },
  { group: 'math', key: 'area-under-curve', label: 'Aire sous la courbe', keywords: 'Area under curve', template: 'math' },
  { group: 'math', key: 'limit', label: 'Limite', keywords: 'Limit', template: 'math' },
  { group: 'math', key: 'distribution', label: 'Distribution', keywords: 'Distribution', template: 'math' },
  { group: 'math', key: 'mean', label: 'Moyenne', keywords: 'Mean', template: 'math' },
  { group: 'math', key: 'median', label: 'Médiane', keywords: 'Median', template: 'math' },
  { group: 'math', key: 'mode', label: 'Mode', keywords: 'Mode', template: 'math' },
  { group: 'math', key: 'standard-deviation', label: 'Écart-type', keywords: 'Standard deviation', template: 'math' },
  { group: 'math', key: 'probability', label: 'Probabilité', keywords: 'Probability', template: 'math' },
  { group: 'math', key: 'histogram', label: 'Histogramme', keywords: 'Histogram', template: 'chart' },
  { group: 'math', key: 'scatter-plot', label: 'Nuage de points', keywords: 'Scatter plot', template: 'chart' },
  { group: 'math', key: 'regression-line', label: 'Droite de régression', keywords: 'Regression line', template: 'arrow' },
  { group: 'science', key: 'atom', label: 'Atome', keywords: 'Atom', template: 'science' },
  { group: 'science', key: 'molecule', label: 'Molécule', keywords: 'Molecule', template: 'science' },
  { group: 'science', key: 'cell', label: 'Cellule', keywords: 'Cell', template: 'science' },
  { group: 'science', key: 'dna', label: 'ADN', keywords: 'DNA', template: 'science' },
  { group: 'science', key: 'chromosome', label: 'Chromosome', keywords: 'Chromosome', template: 'science' },
  { group: 'science', key: 'microscope', label: 'Microscope', keywords: 'Microscope', template: 'lab' },
  { group: 'science', key: 'test-tube', label: 'Éprouvette', keywords: 'Test tube', template: 'lab' },
  { group: 'science', key: 'beaker', label: 'Bécher', keywords: 'Beaker', template: 'lab' },
  { group: 'science', key: 'flask', label: 'Fiole', keywords: 'Flask', template: 'lab' },
  { group: 'science', key: 'bunsen-burner', label: 'Bec Bunsen', keywords: 'Bunsen burner', template: 'lab' },
  { group: 'science', key: 'thermometer', label: 'Thermomètre', keywords: 'Thermometer', template: 'lab' },
  { group: 'science', key: 'magnet', label: 'Aimant', keywords: 'Magnet', template: 'science' },
  { group: 'science', key: 'battery', label: 'Pile électrique', keywords: 'Battery', template: 'science' },
  { group: 'science', key: 'circuit', label: 'Circuit', keywords: 'Circuit', template: 'science' },
  { group: 'science', key: 'light-bulb', label: 'Ampoule', keywords: 'Light bulb', template: 'science' },
  { group: 'science', key: 'gear', label: 'Engrenage', keywords: 'Gear', template: 'body' },
  { group: 'science', key: 'force-arrow', label: 'Flèche de force', keywords: 'Force arrow', template: 'science' },
  { group: 'science', key: 'energy', label: 'Énergie', keywords: 'Energy', template: 'science' },
  { group: 'science', key: 'wave', label: 'Onde', keywords: 'Wave', template: 'science' },
  { group: 'science', key: 'sound-wave', label: 'Onde sonore', keywords: 'Sound wave', template: 'science' },
  { group: 'science', key: 'human-body', label: 'Corps humain', keywords: 'Human body', template: 'body' },
  { group: 'science', key: 'heart', label: 'Cœur', keywords: 'Heart', template: 'body' },
  { group: 'science', key: 'lungs', label: 'Poumons', keywords: 'Lungs', template: 'body' },
  { group: 'science', key: 'stomach', label: 'Estomac', keywords: 'Stomach', template: 'body' },
  { group: 'science', key: 'liver', label: 'Foie', keywords: 'Liver', template: 'body' },
  { group: 'science', key: 'kidney', label: 'Rein', keywords: 'Kidney', template: 'body' },
  { group: 'science', key: 'eye', label: 'Œil', keywords: 'Eye', template: 'body' },
  { group: 'science', key: 'ear', label: 'Oreille', keywords: 'Ear', template: 'body' },
  { group: 'science', key: 'bone', label: 'Os', keywords: 'Bone', template: 'body' },
  { group: 'science', key: 'muscle', label: 'Muscle', keywords: 'Muscle', template: 'body' },
  { group: 'science', key: 'neuron', label: 'Neurone', keywords: 'Neuron', template: 'body' },
  { group: 'science', key: 'blood-cell', label: 'Cellule sanguine', keywords: 'Blood cell', template: 'science' },
  { group: 'science', key: 'plant', label: 'Plante', keywords: 'Plant', template: 'nature' },
  { group: 'science', key: 'leaf', label: 'Feuille', keywords: 'Leaf', template: 'nature' },
  { group: 'science', key: 'root', label: 'Racine', keywords: 'Root', template: 'nature' },
  { group: 'science', key: 'flower', label: 'Fleur', keywords: 'Flower', template: 'nature' },
  { group: 'science', key: 'seed', label: 'Graine', keywords: 'Seed', template: 'nature' },
  { group: 'science', key: 'photosynthesis-diagram', label: 'Schéma de photosynthèse', keywords: 'Photosynthesis diagram', template: 'science' },
  { group: 'science', key: 'food-chain', label: 'Chaîne alimentaire', keywords: 'Food chain', template: 'nature' },
  { group: 'science', key: 'electron', label: 'Électron', keywords: 'Electron', template: 'science' },
  { group: 'science', key: 'proton', label: 'Proton', keywords: 'Proton', template: 'science' },
  { group: 'science', key: 'neutron', label: 'Neutron', keywords: 'Neutron', template: 'science' },
  { group: 'science', key: 'chemical-bond', label: 'Liaison chimique', keywords: 'Chemical bond', template: 'science' },
  { group: 'science', key: 'periodic-table', label: 'Tableau périodique', keywords: 'Periodic table', template: 'science' },
  { group: 'science', key: 'reaction', label: 'Réaction', keywords: 'Reaction', template: 'science' },
  { group: 'science', key: 'solution', label: 'Solution', keywords: 'Solution', template: 'diagram' },
  { group: 'science', key: 'acid', label: 'Acide', keywords: 'Acid', template: 'science' },
  { group: 'science', key: 'base', label: 'Base', keywords: 'Base', template: 'science' },
  { group: 'science', key: 'ph-scale', label: 'Échelle de pH', keywords: 'pH scale', template: 'science' },
  { group: 'science', key: 'chemical-equation', label: 'Équation chimique', keywords: 'Chemical equation', template: 'math' },
  { group: 'science', key: 'motion', label: 'Mouvement', keywords: 'Motion', template: 'science' },
  { group: 'science', key: 'velocity', label: 'Vitesse', keywords: 'Velocity', template: 'science' },
  { group: 'science', key: 'acceleration', label: 'Accélération', keywords: 'Acceleration', template: 'math' },
  { group: 'science', key: 'gravity', label: 'Gravité', keywords: 'Gravity', template: 'science' },
  { group: 'science', key: 'friction', label: 'Frottement', keywords: 'Friction', template: 'science' },
  { group: 'science', key: 'force', label: 'Force', keywords: 'Force', template: 'science' },
  { group: 'science', key: 'mass', label: 'Masse', keywords: 'Mass', template: 'science' },
  { group: 'science', key: 'electricity', label: 'Électricité', keywords: 'Electricity', template: 'science' },
  { group: 'science', key: 'magnetism', label: 'Magnétisme', keywords: 'Magnetism', template: 'science' },
  { group: 'science', key: 'projectile', label: 'Projectile', keywords: 'Projectile', template: 'science' },
  { group: 'science', key: 'pulley', label: 'Poulie', keywords: 'Pulley', template: 'science' },
  { group: 'science', key: 'lever', label: 'Levier', keywords: 'Lever', template: 'science' },
  { group: 'science', key: 'inclined-plane', label: 'Plan incliné', keywords: 'Inclined plane', template: 'arrow' },
  { group: 'technology', key: 'desktop', label: 'Ordinateur de bureau', keywords: 'Desktop', template: 'building' },
  { group: 'technology', key: 'smartphone', label: 'Téléphone intelligent', keywords: 'Smartphone', template: 'device' },
  { group: 'technology', key: 'tablet', label: 'Tablette', keywords: 'Tablet', template: 'device' },
  { group: 'technology', key: 'server', label: 'Serveur', keywords: 'Server', template: 'device' },
  { group: 'technology', key: 'cloud', label: 'Nuage', keywords: 'Cloud', template: 'nature' },
  { group: 'technology', key: 'code', label: 'Code', keywords: 'Code', template: 'tech' },
  { group: 'technology', key: 'browser', label: 'Navigateur', keywords: 'Browser', template: 'device' },
  { group: 'technology', key: 'website', label: 'Site Web', keywords: 'Website', template: 'device' },
  { group: 'technology', key: 'app', label: 'Application', keywords: 'App', template: 'device' },
  { group: 'technology', key: 'api', label: 'API', keywords: 'API', template: 'tech' },
  { group: 'technology', key: 'ai', label: 'Intelligence artificielle', keywords: 'AI', template: 'tech' },
  { group: 'technology', key: 'robot', label: 'Robot', keywords: 'Robot', template: 'tech' },
  { group: 'technology', key: 'chip', label: 'Puce', keywords: 'Chip', template: 'tech' },
  { group: 'technology', key: 'cpu', label: 'Processeur', keywords: 'CPU', template: 'tech' },
  { group: 'technology', key: 'gpu', label: 'Processeur graphique', keywords: 'GPU', template: 'tech' },
  { group: 'technology', key: 'network', label: 'Réseau', keywords: 'Network', template: 'tech' },
  { group: 'technology', key: 'wi-fi', label: 'Wi-Fi', keywords: 'Wi-Fi', template: 'tech' },
  { group: 'technology', key: 'router', label: 'Routeur', keywords: 'Router', template: 'tech' },
  { group: 'technology', key: 'download', label: 'Téléchargement', keywords: 'Download', template: 'tech' },
  { group: 'technology', key: 'upload', label: 'Téléversement', keywords: 'Upload', template: 'tech' },
  { group: 'technology', key: 'search', label: 'Recherche', keywords: 'Search', template: 'body' },
  { group: 'technology', key: 'settings', label: 'Réglages', keywords: 'Settings', template: 'tech' },
  { group: 'technology', key: 'lock', label: 'Cadenas', keywords: 'Lock', template: 'tech' },
  { group: 'technology', key: 'security-shield', label: 'Bouclier de sécurité', keywords: 'Security shield', template: 'tech' },
  { group: 'technology', key: 'password', label: 'Mot de passe', keywords: 'Password', template: 'tech' },
  { group: 'technology', key: 'user-account', label: 'Compte utilisateur', keywords: 'User account', template: 'person' },
  { group: 'technology', key: 'algorithm', label: 'Algorithme', keywords: 'Algorithm', template: 'tech' },
  { group: 'technology', key: 'flowchart', label: 'Organigramme', keywords: 'Flowchart', template: 'tech' },
  { group: 'technology', key: 'terminal', label: 'Terminal', keywords: 'Terminal', template: 'device' },
  { group: 'technology', key: 'bug', label: 'Bogue', keywords: 'Bug', template: 'tech' },
  { group: 'technology', key: 'debugging', label: 'Débogage', keywords: 'Debugging', template: 'tech' },
  { group: 'technology', key: 'notification', label: 'Notification', keywords: 'Notification', template: 'tech' },
  { group: 'technology', key: 'link', label: 'Lien', keywords: 'Link', template: 'tech' },
  { group: 'technology', key: 'qr-code', label: 'Code QR', keywords: 'QR code', template: 'tech' },
  { group: 'technology', key: 'data', label: 'Données', keywords: 'Data', template: 'tech' },
  { group: 'technology', key: 'analytics', label: 'Analytique', keywords: 'Analytics', template: 'tech' },
  { group: 'technology', key: 'dashboard', label: 'Tableau de bord', keywords: 'Dashboard', template: 'building' },
  { group: 'technology', key: 'automation', label: 'Automatisation', keywords: 'Automation', template: 'tech' },
  { group: 'technology', key: 'cloud-storage', label: 'Stockage infonuagique', keywords: 'Cloud storage', template: 'nature' },
  { group: 'technology', key: 'database-connection', label: 'Connexion à la base de données', keywords: 'Database connection', template: 'tech' },
  { group: 'everyday', key: 'house', label: 'Maison', keywords: 'House', template: 'building' },
  { group: 'everyday', key: 'apartment', label: 'Appartement', keywords: 'Apartment', template: 'building' },
  { group: 'everyday', key: 'car', label: 'Voiture', keywords: 'Car', template: 'vehicle' },
  { group: 'everyday', key: 'bus', label: 'Autobus', keywords: 'Bus', template: 'vehicle' },
  { group: 'everyday', key: 'train', label: 'Train', keywords: 'Train', template: 'vehicle' },
  { group: 'everyday', key: 'airplane', label: 'Avion', keywords: 'Airplane', template: 'vehicle' },
  { group: 'everyday', key: 'bicycle', label: 'Vélo', keywords: 'Bicycle', template: 'vehicle' },
  { group: 'everyday', key: 'camera', label: 'Caméra', keywords: 'Camera', template: 'device' },
  { group: 'everyday', key: 'television', label: 'Télévision', keywords: 'Television', template: 'device' },
  { group: 'everyday', key: 'refrigerator', label: 'Réfrigérateur', keywords: 'Refrigerator', template: 'everyday' },
  { group: 'everyday', key: 'stove', label: 'Cuisinière', keywords: 'Stove', template: 'everyday' },
  { group: 'everyday', key: 'bed', label: 'Lit', keywords: 'Bed', template: 'everyday' },
  { group: 'everyday', key: 'lamp', label: 'Lampe', keywords: 'Lamp', template: 'everyday' },
  { group: 'everyday', key: 'shopping-cart', label: 'Panier d’achat', keywords: 'Shopping cart', template: 'vehicle' },
  { group: 'everyday', key: 'shopping-bag', label: 'Sac d’achat', keywords: 'Shopping bag', template: 'everyday' },
  { group: 'everyday', key: 'box', label: 'Boîte', keywords: 'Box', template: 'badge' },
  { group: 'everyday', key: 'package', label: 'Colis', keywords: 'Package', template: 'everyday' },
  { group: 'everyday', key: 'truck', label: 'Camion', keywords: 'Truck', template: 'vehicle' },
  { group: 'everyday', key: 'tools', label: 'Outils', keywords: 'Tools', template: 'everyday' },
  { group: 'everyday', key: 'hammer', label: 'Marteau', keywords: 'Hammer', template: 'everyday' },
  { group: 'everyday', key: 'screwdriver', label: 'Tournevis', keywords: 'Screwdriver', template: 'nature' },
  { group: 'everyday', key: 'wrench', label: 'Clé anglaise', keywords: 'Wrench', template: 'everyday' },
  { group: 'everyday', key: 'building', label: 'Immeuble', keywords: 'Building', template: 'building' },
  { group: 'everyday', key: 'road', label: 'Route', keywords: 'Road', template: 'everyday' },
  { group: 'everyday', key: 'traffic-light', label: 'Feu de circulation', keywords: 'Traffic light', template: 'everyday' },
  { group: 'everyday', key: 'map', label: 'Carte', keywords: 'Map', template: 'everyday' },
  { group: 'everyday', key: 'globe', label: 'Globe', keywords: 'Globe', template: 'everyday' },
  { group: 'everyday', key: 'location-pin', label: 'Repère de lieu', keywords: 'Location pin', template: 'everyday' },
  { group: 'everyday', key: 'hospital', label: 'Hôpital', keywords: 'Hospital', template: 'building' },
  { group: 'everyday', key: 'restaurant', label: 'Restaurant', keywords: 'Restaurant', template: 'building' },
  { group: 'everyday', key: 'grocery-store', label: 'Épicerie', keywords: 'Grocery store', template: 'building' },
  { group: 'everyday', key: 'clothing', label: 'Vêtement', keywords: 'Clothing', template: 'everyday' },
  { group: 'everyday', key: 'food', label: 'Nourriture', keywords: 'Food', template: 'nature' },
  { group: 'everyday', key: 'water', label: 'Eau', keywords: 'Water', template: 'nature' },
  { group: 'everyday', key: 'tree', label: 'Arbre', keywords: 'Tree', template: 'nature' },
  { group: 'everyday', key: 'sun', label: 'Soleil', keywords: 'Sun', template: 'nature' },
  { group: 'everyday', key: 'rain', label: 'Pluie', keywords: 'Rain', template: 'nature' },
  { group: 'everyday', key: 'fire', label: 'Feu', keywords: 'Fire', template: 'nature' },
  { group: 'everyday', key: 'mountain', label: 'Montagne', keywords: 'Mountain', template: 'nature' },
  { group: 'everyday', key: 'river', label: 'Rivière', keywords: 'River', template: 'nature' },
  { group: 'everyday', key: 'earth', label: 'Terre', keywords: 'Earth', template: 'body' },
  { group: 'everyday', key: 'moon', label: 'Lune', keywords: 'Moon', template: 'nature' },
  { group: 'everyday', key: 'planet', label: 'Planète', keywords: 'Planet', template: 'nature' },
  { group: 'diagrams', key: 'straight-arrow', label: 'Flèche droite', keywords: 'Straight arrow', template: 'tech' },
  { group: 'diagrams', key: 'curved-arrow', label: 'Flèche courbe', keywords: 'Curved arrow', template: 'arrow' },
  { group: 'diagrams', key: 'double-arrow', label: 'Double flèche', keywords: 'Double arrow', template: 'arrow' },
  { group: 'diagrams', key: 'dashed-arrow', label: 'Flèche pointillée', keywords: 'Dashed arrow', template: 'arrow' },
  { group: 'diagrams', key: 'thick-arrow', label: 'Flèche épaisse', keywords: 'Thick arrow', template: 'arrow' },
  { group: 'diagrams', key: 'thin-arrow', label: 'Flèche fine', keywords: 'Thin arrow', template: 'arrow' },
  { group: 'diagrams', key: 'circular-arrow', label: 'Flèche circulaire', keywords: 'Circular arrow', template: 'arrow' },
  { group: 'diagrams', key: 'up-arrow', label: 'Flèche vers le haut', keywords: 'Up arrow', template: 'arrow' },
  { group: 'diagrams', key: 'down-arrow', label: 'Flèche vers le bas', keywords: 'Down arrow', template: 'arrow' },
  { group: 'diagrams', key: 'left-arrow', label: 'Flèche vers la gauche', keywords: 'Left arrow', template: 'arrow' },
  { group: 'diagrams', key: 'right-arrow', label: 'Flèche vers la droite', keywords: 'Right arrow', template: 'arrow' },
  { group: 'diagrams', key: 'line', label: 'Ligne', keywords: 'Line', template: 'arrow' },
  { group: 'diagrams', key: 'dashed-line', label: 'Ligne pointillée', keywords: 'Dashed line', template: 'arrow' },
  { group: 'diagrams', key: 'curved-connector', label: 'Connecteur courbe', keywords: 'Curved connector', template: 'arrow' },
  { group: 'diagrams', key: 'branch', label: 'Branchement', keywords: 'Branch', template: 'arrow' },
  { group: 'diagrams', key: 'junction', label: 'Jonction', keywords: 'Junction', template: 'arrow' },
  { group: 'diagrams', key: 'flow-connector', label: 'Connecteur de flux', keywords: 'Flow connector', template: 'arrow' },
  { group: 'diagrams', key: '2-column-comparison', label: 'Comparaison en deux colonnes', keywords: '2-column comparison', template: 'diagram' },
  { group: 'diagrams', key: '3-step-process', label: 'Processus en trois étapes', keywords: '3-step process', template: 'diagram' },
  { group: 'diagrams', key: '4-step-process', label: 'Processus en quatre étapes', keywords: '4-step process', template: 'diagram' },
  { group: 'diagrams', key: 'timeline', label: 'Frise chronologique', keywords: 'Timeline', template: 'arrow' },
  { group: 'diagrams', key: 'cycle', label: 'Cycle', keywords: 'Cycle', template: 'diagram' },
  { group: 'diagrams', key: 'hierarchy', label: 'Hiérarchie', keywords: 'Hierarchy', template: 'diagram' },
  { group: 'diagrams', key: 'funnel', label: 'Entonnoir', keywords: 'Funnel', template: 'diagram' },
  { group: 'diagrams', key: 'pyramid', label: 'Pyramide', keywords: 'Pyramid', template: 'diagram' },
  { group: 'diagrams', key: 'venn-diagram', label: 'Diagramme de Venn', keywords: 'Venn diagram', template: 'diagram' },
  { group: 'diagrams', key: 'matrix', label: 'Matrice', keywords: 'Matrix', template: 'diagram' },
  { group: 'diagrams', key: 'decision-tree', label: 'Arbre de décision', keywords: 'Decision tree', template: 'nature' },
  { group: 'diagrams', key: 'cause-effect', label: 'Cause et effet', keywords: 'Cause/effect', template: 'diagram' },
  { group: 'diagrams', key: 'input-process-output', label: 'Entrée → traitement → sortie', keywords: 'Input → process → output', template: 'arrow' },
  { group: 'diagrams', key: 'before-after', label: 'Avant → après', keywords: 'Before → after', template: 'diagram' },
  { group: 'diagrams', key: 'problem-solution', label: 'Problème → solution', keywords: 'Problem → solution', template: 'diagram' },
  { group: 'diagrams', key: 'question-answer', label: 'Question → réponse', keywords: 'Question → answer', template: 'diagram' },
  { group: 'diagrams', key: 'main-idea-examples', label: 'Idée principale → exemples', keywords: 'Main idea → examples', template: 'tech' },
  { group: 'emphasis', key: 'circle-around-object', label: 'Cercle autour d’un élément', keywords: 'Circle around object', template: 'shape' },
  { group: 'emphasis', key: 'rectangle-around-object', label: 'Cadre autour d’un élément', keywords: 'Rectangle around object', template: 'shape' },
  { group: 'emphasis', key: 'underline', label: 'Soulignement', keywords: 'Underline', template: 'arrow' },
  { group: 'emphasis', key: 'highlight', label: 'Surlignage', keywords: 'Highlight', template: 'callout' },
  { group: 'emphasis', key: 'starburst', label: 'Éclat en étoile', keywords: 'Starburst', template: 'badge' },
  { group: 'emphasis', key: 'exclamation-mark', label: 'Point d’exclamation', keywords: 'Exclamation mark', template: 'badge' },
  { group: 'emphasis', key: 'checkmark', label: 'Coche', keywords: 'Checkmark', template: 'badge' },
  { group: 'emphasis', key: 'x', label: 'Croix', keywords: 'X', template: 'badge' },
  { group: 'emphasis', key: 'warning-triangle', label: 'Triangle d’avertissement', keywords: 'Warning triangle', template: 'shape' },
  { group: 'emphasis', key: 'attention-rays', label: 'Rayons d’attention', keywords: 'Attention rays', template: 'emphasis' },
  { group: 'emphasis', key: 'lightbulb-rays', label: 'Rayons d’ampoule', keywords: 'Lightbulb rays', template: 'emphasis' },
  { group: 'emphasis', key: 'zoom-circle', label: 'Cercle de zoom', keywords: 'Zoom circle', template: 'shape' },
  { group: 'emphasis', key: 'speech-bubble', label: 'Bulle de dialogue', keywords: 'Speech bubble', template: 'callout' },
  { group: 'emphasis', key: 'caption-box', label: 'Boîte de légende', keywords: 'Caption box', template: 'badge' },
  { group: 'emphasis', key: 'sticky-note', label: 'Note autocollante', keywords: 'Sticky note', template: 'callout' },
  { group: 'emphasis', key: 'label', label: 'Étiquette', keywords: 'Label', template: 'callout' },
  { group: 'emphasis', key: 'number-marker', label: 'Repère numéroté', keywords: 'Number marker', template: 'writing' },
  { group: 'emphasis', key: 'step-marker', label: 'Repère d’étape', keywords: 'Step marker', template: 'writing' },
  { group: 'emphasis', key: 'hand-drawn-arrow', label: 'Flèche dessinée à la main', keywords: 'Hand-drawn arrow', template: 'arrow' },
  { group: 'emphasis', key: 'hand-drawn-circle', label: 'Cercle dessiné à la main', keywords: 'Hand-drawn circle', template: 'shape' },
  { group: 'emphasis', key: 'hand-drawn-underline', label: 'Soulignement dessiné à la main', keywords: 'Hand-drawn underline', template: 'arrow' },
  { group: 'emphasis', key: 'handwritten-annotation', label: 'Annotation manuscrite', keywords: 'Handwritten annotation', template: 'callout' },
  { group: 'emphasis', key: 'redraw-reveal-mask', label: 'Masque de révélation', keywords: 'Redraw/reveal mask', template: 'emphasis' },
  { group: 'emphasis', key: 'spotlight', label: 'Projecteur', keywords: 'Spotlight', template: 'callout' },
  { group: 'emphasis', key: 'glow', label: 'Halo', keywords: 'Glow', template: 'callout' },
  { group: 'emphasis', key: 'pointer', label: 'Pointeur', keywords: 'Pointer', template: 'callout' },
  { group: 'emphasis', key: 'bracket', label: 'Crochet', keywords: 'Bracket', template: 'callout' },
  { group: 'emphasis', key: 'curly-brace', label: 'Accolade', keywords: 'Curly brace', template: 'callout' },
  { group: 'emphasis', key: 'parentheses', label: 'Parenthèses', keywords: 'Parentheses', template: 'callout' },
  { group: 'emphasis', key: 'formula-box', label: 'Cadre de formule', keywords: 'Formula box', template: 'document' },
  { group: 'emphasis', key: 'important-box', label: 'Encadré important', keywords: 'Important box', template: 'badge' },
  { group: 'emphasis', key: 'remember-badge', label: 'Pastille « À retenir »', keywords: '“Remember” badge', template: 'badge' },
  { group: 'charts', key: 'bar-chart', label: 'Graphique à barres', keywords: 'Bar chart', template: 'chart' },
  { group: 'charts', key: 'horizontal-bar-chart', label: 'Barres horizontales', keywords: 'Horizontal bar chart', template: 'chart' },
  { group: 'charts', key: 'stacked-bar-chart', label: 'Barres empilées', keywords: 'Stacked bar chart', template: 'chart' },
  { group: 'charts', key: 'line-chart', label: 'Graphique linéaire', keywords: 'Line chart', template: 'arrow' },
  { group: 'charts', key: 'area-chart', label: 'Graphique en aires', keywords: 'Area chart', template: 'chart' },
  { group: 'charts', key: 'pie-chart', label: 'Diagramme circulaire', keywords: 'Pie chart', template: 'chart' },
  { group: 'charts', key: 'donut-chart', label: 'Diagramme en anneau', keywords: 'Donut chart', template: 'chart' },
  { group: 'charts', key: 'box-plot', label: 'Boîte à moustaches', keywords: 'Box plot', template: 'chart' },
  { group: 'charts', key: 'bubble-chart', label: 'Graphique à bulles', keywords: 'Bubble chart', template: 'chart' },
  { group: 'charts', key: 'radar-chart', label: 'Graphique radar', keywords: 'Radar chart', template: 'chart' },
  { group: 'charts', key: 'waterfall-chart', label: 'Graphique en cascade', keywords: 'Waterfall chart', template: 'nature' },
  { group: 'charts', key: 'timeline-chart', label: 'Graphique chronologique', keywords: 'Timeline chart', template: 'arrow' },
  { group: 'charts', key: 'progress-bar', label: 'Barre de progression', keywords: 'Progress bar', template: 'charts' },
  { group: 'charts', key: 'gauge', label: 'Jauge', keywords: 'Gauge', template: 'chart' },
  { group: 'charts', key: 'kpi-card', label: 'Carte d’indicateur', keywords: 'KPI card', template: 'vehicle' },
  { group: 'charts', key: 'percentage-circle', label: 'Cercle de pourcentage', keywords: 'Percentage circle', template: 'math' },
  { group: 'charts', key: 'comparison-bars', label: 'Barres de comparaison', keywords: 'Comparison bars', template: 'diagram' },
  { group: 'charts', key: 'before-after-bars', label: 'Barres avant/après', keywords: 'Before/after bars', template: 'diagram' },
  { group: 'charts', key: 'growth-arrow', label: 'Flèche de croissance', keywords: 'Growth arrow', template: 'arrow' },
  { group: 'charts', key: 'decline-arrow', label: 'Flèche de baisse', keywords: 'Decline arrow', template: 'arrow' },
  { group: 'charts', key: 'trend-line', label: 'Ligne de tendance', keywords: 'Trend line', template: 'arrow' },
  { group: 'charts', key: 'axis', label: 'Axes', keywords: 'Axis', template: 'shape' },
  { group: 'charts', key: 'grid', label: 'Grille', keywords: 'Grid', template: 'chart' },
  { group: 'charts', key: 'legend', label: 'Légende', keywords: 'Legend', template: 'chart' },
  { group: 'charts', key: 'data-point', label: 'Point de données', keywords: 'Data point', template: 'tech' },
  { group: 'charts', key: 'heatmap', label: 'Carte thermique', keywords: 'Heatmap', template: 'chart' },
  { group: 'charts', key: 'distribution-curve', label: 'Courbe de distribution', keywords: 'Distribution curve', template: 'chart' },
  { group: 'charts', key: 'bell-curve', label: 'Courbe en cloche', keywords: 'Bell curve', template: 'chart' },
  { group: 'charts', key: 'normal-distribution', label: 'Distribution normale', keywords: 'Normal distribution', template: 'charts' },
  { group: 'charts', key: 'probability-tree', label: 'Arbre de probabilités', keywords: 'Probability tree', template: 'math' },
  { group: 'emotions', key: 'happy', label: 'Heureux·se', keywords: 'Happy', template: 'device' },
  { group: 'emotions', key: 'sad', label: 'Triste', keywords: 'Sad', template: 'emotion' },
  { group: 'emotions', key: 'confused', label: 'Confus·e', keywords: 'Confused', template: 'emotion' },
  { group: 'emotions', key: 'surprised', label: 'Surpris·e', keywords: 'Surprised', template: 'emotion' },
  { group: 'emotions', key: 'excited', label: 'Enthousiaste', keywords: 'Excited', template: 'emotion' },
  { group: 'emotions', key: 'thinking', label: 'En réflexion', keywords: 'Thinking', template: 'emotion' },
  { group: 'emotions', key: 'curious', label: 'Curieux·se', keywords: 'Curious', template: 'emotion' },
  { group: 'emotions', key: 'worried', label: 'Inquiet·ète', keywords: 'Worried', template: 'emotion' },
  { group: 'emotions', key: 'frustrated', label: 'Frustré·e', keywords: 'Frustrated', template: 'emotion' },
  { group: 'emotions', key: 'confident', label: 'Confiant·e', keywords: 'Confident', template: 'emotion' },
  { group: 'emotions', key: 'celebrating', label: 'Célèbre une réussite', keywords: 'Celebrating', template: 'emotion' },
  { group: 'emotions', key: 'questioning', label: 'S’interroge', keywords: 'Questioning', template: 'diagram' },
  { group: 'emotions', key: 'shocked', label: 'Choqué·e', keywords: 'Shocked', template: 'emotion' },
  { group: 'emotions', key: 'sleepy', label: 'Fatigué·e', keywords: 'Sleepy', template: 'emotion' },
  { group: 'emotions', key: 'focused', label: 'Concentré·e', keywords: 'Focused', template: 'emotion' },
  { group: 'emotions', key: 'understanding', label: 'Comprend', keywords: 'Understanding', template: 'emotion' },
  { group: 'emotions', key: 'mistake', label: 'Erreur', keywords: 'Mistake', template: 'emotion' },
  { group: 'emotions', key: 'correct', label: 'Correct', keywords: 'Correct', template: 'emotion' },
  { group: 'emotions', key: 'eureka', label: 'Découverte', keywords: 'Eureka', template: 'emotion' },
  { group: 'emotions', key: 'warning', label: 'Avertissement', keywords: 'Warning', template: 'badge' },
  { group: 'emotions', key: 'oops', label: '« Oups »', keywords: '“Oops”', template: 'emotion' },
  { group: 'emotions', key: 'aha', label: '« Ah-ha ! »', keywords: '“Aha!”', template: 'emotion' },
  { group: 'emotions', key: 'important', label: '« Important »', keywords: '“Important”', template: 'badge' },
  { group: 'emotions', key: 'remember', label: '« À retenir »', keywords: '“Remember”', template: 'badge' },
  { group: 'emotions', key: 'why', label: '« Pourquoi ? »', keywords: '“Why?”', template: 'emotions' },
  { group: 'concepts', key: 'idea', label: 'Idée', keywords: 'Idea', template: 'concept' },
  { group: 'concepts', key: 'goal', label: 'Objectif', keywords: 'Goal', template: 'concept' },
  { group: 'concepts', key: 'problem', label: 'Problème', keywords: 'Problem', template: 'diagram' },
  { group: 'concepts', key: 'cause', label: 'Cause', keywords: 'Cause', template: 'diagram' },
  { group: 'concepts', key: 'effect', label: 'Effet', keywords: 'Effect', template: 'diagram' },
  { group: 'concepts', key: 'input', label: 'Entrée', keywords: 'Input', template: 'arrow' },
  { group: 'concepts', key: 'output', label: 'Sortie', keywords: 'Output', template: 'arrow' },
  { group: 'concepts', key: 'process', label: 'Processus', keywords: 'Process', template: 'diagram' },
  { group: 'concepts', key: 'change', label: 'Changement', keywords: 'Change', template: 'arrow' },
  { group: 'concepts', key: 'growth', label: 'Croissance', keywords: 'Growth', template: 'arrow' },
  { group: 'concepts', key: 'decline', label: 'Baisse', keywords: 'Decline', template: 'arrow' },
  { group: 'concepts', key: 'connection', label: 'Connexion', keywords: 'Connection', template: 'concepts' },
  { group: 'concepts', key: 'separation', label: 'Séparation', keywords: 'Separation', template: 'math' },
  { group: 'concepts', key: 'comparison', label: 'Comparaison', keywords: 'Comparison', template: 'diagram' },
  { group: 'concepts', key: 'increase', label: 'Augmentation', keywords: 'Increase', template: 'arrow' },
  { group: 'concepts', key: 'decrease', label: 'Diminution', keywords: 'Decrease', template: 'arrow' },
  { group: 'concepts', key: 'time', label: 'Temps', keywords: 'Time', template: 'concepts' },
  { group: 'concepts', key: 'speed', label: 'Vitesse', keywords: 'Speed', template: 'arrow' },
  { group: 'concepts', key: 'risk', label: 'Risque', keywords: 'Risk', template: 'concept' },
  { group: 'concepts', key: 'opportunity', label: 'Occasion', keywords: 'Opportunity', template: 'concept' },
  { group: 'concepts', key: 'success', label: 'Réussite', keywords: 'Success', template: 'concept' },
  { group: 'concepts', key: 'failure', label: 'Échec', keywords: 'Failure', template: 'tech' },
  { group: 'concepts', key: 'choice', label: 'Choix', keywords: 'Choice', template: 'concept' },
  { group: 'concepts', key: 'decision', label: 'Décision', keywords: 'Decision', template: 'diagram' },
  { group: 'concepts', key: 'priority', label: 'Priorité', keywords: 'Priority', template: 'concept' },
  { group: 'concepts', key: 'information', label: 'Information', keywords: 'Information', template: 'document' },
  { group: 'concepts', key: 'knowledge', label: 'Connaissances', keywords: 'Knowledge', template: 'concept' },
  { group: 'concepts', key: 'memory', label: 'Mémoire', keywords: 'Memory', template: 'concept' },
  { group: 'concepts', key: 'question', label: 'Question', keywords: 'Question', template: 'diagram' },
  { group: 'concepts', key: 'answer', label: 'Réponse', keywords: 'Answer', template: 'diagram' },
  { group: 'concepts', key: 'evidence', label: 'Preuve', keywords: 'Evidence', template: 'concept' },
  { group: 'concepts', key: 'example', label: 'Exemple', keywords: 'Example', template: 'badge' },
  { group: 'concepts', key: 'rule', label: 'Règle', keywords: 'Rule', template: 'concept' },
  { group: 'concepts', key: 'exception', label: 'Exception', keywords: 'Exception', template: 'badge' },
  { group: 'concepts', key: 'summary', label: 'Résumé', keywords: 'Summary', template: 'concept' },
  { group: 'concepts', key: 'key-point', label: 'Point clé', keywords: 'Key point', template: 'concept' },
  { group: 'concepts', key: 'important', label: 'Important', keywords: 'Important', template: 'badge' },
  { group: 'concepts', key: 'conclusion', label: 'Conclusion', keywords: 'Conclusion', template: 'concept' },
];
