// Clear French titles for the 327 scenarios (key = scenario number).
export const SCENARIO_FR: Record<number, string> = {
  1: "Étudiant·e debout, posture neutre", 2: "Étudiant·e debout qui explique", 3: "Étudiant·e debout qui présente", 4: "Étudiant·e debout qui pointe du doigt", 5: "Étudiant·e debout qui réfléchit", 6: "Étudiant·e debout, l'air confus", 7: "Étudiant·e debout, surpris·e", 8: "Étudiant·e debout, souriant·e et content·e", 9: "Étudiant·e debout qui pose une question", 10: "Étudiant·e debout qui répond", 11: "Étudiant·e debout qui lève la main", 12: "Étudiant·e debout qui écoute", 13: "Étudiant·e debout qui parle", 14: "Étudiant·e debout qui lit un livre", 15: "Étudiant·e debout qui écrit dans un cahier",
  16: "Étudiant·e assis·e à un bureau", 17: "Étudiant·e assis·e qui écrit", 18: "Étudiant·e assis·e qui lit", 19: "Étudiant·e assis·e qui réfléchit", 20: "Étudiant·e assis·e, l'air confus", 21: "Étudiant·e assis·e qui écoute", 22: "Étudiant·e assis·e qui lève la main", 23: "Étudiant·e assis·e qui répond", 24: "Étudiant·e assis·e sur son ordinateur portable", 25: "Étudiant·e assis·e avec une calculatrice", 26: "Étudiant·e assis·e qui regarde son téléphone", 27: "Étudiant·e assis·e qui prend des notes", 28: "Étudiant·e assis·e qui étudie", 29: "Étudiant·e assis·e qui fait ses devoirs", 30: "Étudiant·e assis·e qui célèbre une réussite",
  31: "Étudiant·e qui parle à l'enseignant·e", 32: "Étudiant·e qui écoute l'enseignant·e", 33: "Étudiant·e qui pose une question à l'enseignant·e", 34: "Étudiant·e qui répond à l'enseignant·e", 35: "Deux étudiant·es qui discutent", 36: "Deux étudiant·es qui étudient ensemble", 37: "Deux étudiant·es devant un ordinateur portable", 38: "Deux étudiant·es qui regardent un document", 39: "Étudiant·e qui aide un·e camarade", 40: "Étudiant·e qui présente à un·e camarade", 41: "Étudiant·e qui interviewe un·e camarade", 42: "Étudiant·es qui collaborent autour d'un bureau",
  43: "Enseignant·e debout à côté du tableau", 44: "Enseignant·e qui écrit au tableau", 45: "Enseignant·e qui pointe le tableau", 46: "Enseignant·e qui présente devant la classe", 47: "Enseignant·e qui explique une formule", 48: "Enseignant·e qui explique un schéma", 49: "Enseignant·e qui explique un graphique", 50: "Enseignant·e qui tient un manuel", 51: "Enseignant·e qui tient des feuilles", 52: "Enseignant·e sur un ordinateur portable", 53: "Enseignant·e assis·e à son bureau", 54: "Enseignant·e qui corrige une copie", 55: "Enseignant·e qui lit une copie", 56: "Enseignant·e qui parle à un·e étudiant·e", 57: "Enseignant·e qui écoute un·e étudiant·e", 58: "Enseignant·e qui répond à un·e étudiant·e", 59: "Enseignant·e qui désigne un·e étudiant·e", 60: "Enseignant·e qui pose une question", 61: "Enseignant·e qui lève la main", 62: "Enseignant·e qui montre un objet", 63: "Enseignant·e qui fait une expérience", 64: "Enseignant·e qui présente avec un projecteur", 65: "Enseignant·e debout à côté d'un écran", 66: "Enseignant·e face à un petit groupe", 67: "Enseignant·e face à toute la classe",
  68: "Salle de classe vide", 69: "Salle de classe avec étudiant·es assis", 70: "Enseignant·e devant la classe", 71: "Enseignant·e + étudiant·es + tableau", 72: "Enseignant·e + étudiant·es + projecteur", 73: "Étudiant·e à son pupitre en classe", 74: "Deux étudiant·es à leurs pupitres", 75: "Étudiant·e qui lève la main en classe", 76: "Étudiant·e qui présente devant la classe", 77: "Étudiant·e qui répond à l'enseignant·e en classe", 78: "Discussion de groupe", 79: "Projet de groupe", 80: "Étudiant·e qui écrit au tableau de la classe", 81: "Enseignant·e qui distribue des copies", 82: "Enseignant·e qui ramasse des copies", 83: "Étudiant·e qui passe un examen", 84: "Étudiant·e qui lit son examen", 85: "Étudiant·e qui remet son examen", 86: "Classe avec tableau de maths", 87: "Classe avec tableau de sciences", 88: "Classe avec frise chronologique d'histoire", 89: "Classe pendant un cours de langue",
  90: "Étudiant·e qui étudie à son bureau", 91: "Étudiant·e qui lit un manuel", 92: "Étudiant·e qui surligne un manuel", 93: "Étudiant·e qui écrit des notes", 94: "Étudiant·e qui organise ses notes", 95: "Étudiant·e sur un ordinateur portable", 96: "Étudiant·e sur une tablette", 97: "Étudiant·e avec une calculatrice", 98: "Étudiant·e qui compare deux documents", 99: "Étudiant·e qui regarde une courbe", 100: "Étudiant·e qui regarde un diagramme", 101: "Étudiant·e qui résout une équation", 102: "Étudiant·e qui dessine un schéma", 103: "Étudiant·e avec une règle", 104: "Étudiant·e avec un compas", 105: "Étudiant·e avec des cartes-mémoire", 106: "Étudiant·e qui prépare une présentation", 107: "Étudiant·e qui vérifie sa réponse", 108: "Étudiant·e qui corrige une erreur", 109: "Étudiant·e qui célèbre une bonne réponse",
  110: "Étudiant·e + tableau d'équations", 111: "Étudiant·e + figure géométrique", 112: "Étudiant·e + droite numérique", 113: "Étudiant·e + plan cartésien", 114: "Étudiant·e + graphique", 115: "Enseignant·e + tableau d'équations", 116: "Enseignant·e + tableau de géométrie", 117: "Enseignant·e + diagramme statistique", 118: "Enseignant·e + schéma de probabilités", 119: "Enseignant·e + calculatrice", 120: "Étudiant·e + calculatrice", 121: "Étudiant·e + règle", 122: "Étudiant·e + rapporteur d'angle", 123: "Étudiant·e + compas", 124: "Enseignant·e qui montre une mesure", 125: "Étudiant·e qui mesure un objet", 126: "Étudiant·e qui trace une forme géométrique", 127: "Étudiant·e qui trace un graphique", 128: "Enseignant·e qui pointe un graphique", 129: "Étudiant·e qui compare deux graphiques",
  130: "Scientifique à la paillasse du labo", 131: "Scientifique qui examine un échantillon", 132: "Scientifique au microscope", 133: "Scientifique avec une éprouvette", 134: "Scientifique avec un bécher", 135: "Scientifique qui note ses observations", 136: "Scientifique qui examine un graphique", 137: "Scientifique qui explique une expérience", 138: "Enseignant·e qui fait une expérience", 139: "Étudiant·e qui fait une expérience", 140: "Étudiant·e qui observe une expérience", 141: "Étudiant·e qui examine un schéma de cellule", 142: "Scientifique qui examine une cellule", 143: "Scientifique au microscope (variante)", 144: "Enseignant·e qui explique l'anatomie", 145: "Étudiant·e qui étudie l'anatomie", 146: "Étudiant·e qui examine une plante", 147: "Scientifique qui examine une plante", 148: "Scientifique avec un modèle d'ADN", 149: "Étudiant·e qui étudie un modèle d'ADN", 150: "Enseignant·e qui explique le corps humain", 151: "Médecin qui explique l'anatomie", 152: "Scientifique qui mélange des produits chimiques", 153: "Scientifique qui tient une éprouvette", 154: "Scientifique avec un bécher (variante)", 155: "Scientifique avec une fiole", 156: "Scientifique avec du matériel de labo", 157: "Étudiant·e qui fait une expérience de chimie", 158: "Enseignant·e qui montre une réaction chimique", 159: "Scientifique qui examine un modèle moléculaire", 160: "Enseignant·e qui démontre une force", 161: "Étudiant·e qui mesure une force", 162: "Étudiant·e qui mesure une distance", 163: "Étudiant·e avec un chronomètre", 164: "Étudiant·e qui étudie un mouvement", 165: "Enseignant·e qui explique la mécanique", 166: "Étudiant·e qui examine un circuit", 167: "Étudiant·e qui branche des composants électriques", 168: "Scientifique qui démontre le magnétisme",
  169: "Médecin qui parle à un·e patient·e", 170: "Médecin qui examine un·e patient·e", 171: "Médecin qui écoute un·e patient·e", 172: "Médecin avec un stéthoscope", 173: "Médecin qui lit un dossier médical", 174: "Médecin qui explique un diagnostic", 175: "Infirmier·ère qui parle à un·e patient·e", 176: "Infirmier·ère qui vérifie un·e patient·e", 177: "Étudiant·e qui étudie l'anatomie (santé)", 178: "Étudiant·e en médecine avec un modèle anatomique", 179: "Chirurgien·ne au bloc opératoire", 180: "Scientifique qui examine un échantillon médical", 181: "Pharmacien·ne qui explique un médicament", 182: "Patient·e qui lit un document médical",
  183: "Gestionnaire à son bureau", 184: "Gestionnaire qui présente", 185: "Gestionnaire qui pointe un graphique", 186: "Gestionnaire qui explique une courbe", 187: "Deux gestionnaires qui discutent", 188: "Réunion d'affaires", 189: "Équipe autour d'une table de conférence", 190: "Gestionnaire qui présente à son équipe", 191: "Employé·e qui présente à son/sa gestionnaire", 192: "Client·e + vendeur·se", 193: "Négociation entre deux personnes", 194: "Entrevue", 195: "Entrevue d'embauche", 196: "Employé·e à l'ordinateur", 197: "Gestionnaire qui révise des documents", 198: "Gestionnaire qui fait des calculs", 199: "Gestionnaire qui examine un rapport financier", 200: "Gestionnaire avec une calculatrice",
  201: "Comptable à son bureau", 202: "Comptable avec une calculatrice", 203: "Comptable sur un ordinateur portable", 204: "Comptable qui révise des états financiers", 205: "Comptable qui vérifie des reçus", 206: "Comptable qui vérifie des factures", 207: "Comptable qui classe des documents", 208: "Comptable qui fait un rapprochement", 209: "Comptable qui examine un relevé bancaire", 210: "Comptable qui explique un état financier", 211: "Comptable qui présente des résultats", 212: "Comptable qui examine le grand livre", 213: "Comptable qui calcule des coûts", 214: "Comptable qui examine l'inventaire", 215: "Comptable qui compte l'inventaire", 216: "Comptable qui traite des factures", 217: "Comptable qui discute avec un·e client·e", 218: "Comptable qui révise des documents fiscaux", 219: "Comptable qui examine un graphique", 220: "Comptable qui présente un graphique financier",
  221: "Ingénieur·e à son poste de travail", 222: "Ingénieur·e qui examine un plan", 223: "Ingénieur·e qui dessine un plan technique", 224: "Ingénieur·e à l'ordinateur", 225: "Ingénieur·e qui examine une machine", 226: "Ingénieur·e qui inspecte un équipement", 227: "Ingénieur·e avec casque et gilet de sécurité", 228: "Ingénieur·e qui présente un projet", 229: "Deux ingénieur·es qui discutent d'un plan", 230: "Équipe d'ingénieur·es autour d'une table", 231: "Ingénieur·e qui mesure un objet", 232: "Ingénieur·e avec un instrument de mesure", 233: "Ingénieur·e sur un chantier", 234: "Ingénieur·e qui examine une maquette",
  235: "Avocat·e à son bureau", 236: "Avocat·e qui révise un document", 237: "Avocat·e qui plaide", 238: "Avocat·e qui parle à un·e client·e", 239: "Avocat·e et client·e autour d'un document", 240: "Deux avocat·es qui discutent", 241: "Personne qui signe un document", 242: "Personne qui lit un contrat", 243: "Enseignant·e qui explique un document historique", 244: "Étudiant·e qui examine un document historique", 245: "Enseignant·e qui explique une frise chronologique", 246: "Étudiant·e qui examine une carte", 247: "Enseignant·e qui pointe une carte", 248: "Étudiant·e qui présente un projet d'histoire", 249: "Discussion en classe",
  250: "Enseignant·e qui pointe une carte (géo)", 251: "Étudiant·e qui examine une carte (géo)", 252: "Étudiant·e avec un globe", 253: "Enseignant·e avec un globe", 254: "Géographe qui examine une carte", 255: "Scientifique qui étudie l'environnement", 256: "Scientifique qui prélève un échantillon", 257: "Scientifique qui examine un écosystème", 258: "Étudiant·e qui observe la nature", 259: "Scientifique qui examine des données météo", 260: "Météorologue qui présente une carte météo",
  261: "Étudiant·e qui programme à l'ordinateur", 262: "Développeur·se sur un portable", 263: "Enseignant·e qui explique du code", 264: "Étudiant·e qui regarde du code", 265: "Étudiant·e qui corrige un bogue", 266: "Développeur·se qui examine un schéma", 267: "Deux développeur·ses qui collaborent", 268: "Programmeur·se qui présente une architecture", 269: "Étudiant·e qui apprend l'informatique", 270: "Personne devant un schéma de base de données", 271: "Analyste en cybersécurité à l'ordinateur", 272: "Analyste de données devant un tableau de bord",
  273: "Enseignant·e qui parle à un·e étudiant·e (langues)", 274: "Étudiant·e qui parle à l'enseignant·e (langues)", 275: "Deux personnes en conversation", 276: "Étudiant·e qui lit un texte", 277: "Étudiant·e qui écrit une phrase", 278: "Étudiant·e qui pratique sa prononciation", 279: "Enseignant·e qui corrige une phrase", 280: "Étudiant·e qui fait une présentation orale", 281: "Étudiant·e qui écoute quelqu'un parler", 282: "Étudiant·e avec un casque audio", 283: "Enseignant·e qui pointe un tableau de vocabulaire", 284: "Étudiant·es qui pratiquent une conversation",
  285: "Étudiant·e qui dessine", 286: "Enseignant·e qui montre comment dessiner", 287: "Étudiant·e qui peint", 288: "Artiste qui peint", 289: "Étudiant·e avec un appareil photo", 290: "Étudiant·e qui observe une œuvre", 291: "Enseignant·e qui commente une œuvre", 292: "Étudiant·e qui joue d'un instrument", 293: "Enseignant·e qui montre un instrument", 294: "Étudiant·e sur scène", 295: "Étudiant·e qui travaille sur un design",
  296: "Personne au microscope", 297: "Personne au télescope", 298: "Personne avec une centrifugeuse", 299: "Personne à la paillasse du labo", 300: "Personne à un poste informatique", 301: "Personne avec un instrument de mesure", 302: "Personne qui fait fonctionner une machine", 303: "Personne qui inspecte une machine", 304: "Personne qui tient une éprouvette", 305: "Personne qui tient un bécher", 306: "Personne qui examine un spécimen", 307: "Personne qui note une mesure",
  308: "Personne qui réfléchit", 309: "Personne qui pose une question", 310: "Personne qui explique", 311: "Personne qui compare deux choses", 312: "Personne qui prend une décision", 313: "Personne qui découvre quelque chose", 314: "Personne qui se trompe", 315: "Personne qui corrige son erreur", 316: "Personne qui résout un problème", 317: "Personne confuse", 318: "Personne qui comprend", 319: "Personne qui célèbre une réussite", 320: "Personne qui collabore", 321: "Personne qui fait des recherches", 322: "Personne qui lit", 323: "Personne qui écrit", 324: "Personne qui présente", 325: "Personne qui écoute", 326: "Personne qui observe", 327: "Personne qui calcule",
};

const has = (t: string, re: RegExp) => re.test(t);

/** Plain-French description: how many people, which setting. */
export function describeScenario(title: string, multi: boolean): string {
  const t = title.toLowerCase();
  const people = has(t, /group|team|class(room)? with|students \+|\+ students|classroom discussion|meeting|practicing conversation/) ? "Groupe"
    : has(t, /^empty/) ? "Personne"
    : multi ? "2 personnes" : "1 personne seule";
  const setting = has(t, /classroom|class\b|to class|in class/) ? "salle de classe"
    : has(t, /lab|bench|microscope|test tube|beaker|flask|centrifuge|chemic/) ? "laboratoire"
    : has(t, /operating|patient|hospital/) ? "milieu médical"
    : has(t, /construction/) ? "chantier"
    : has(t, /conference|meeting/) ? "salle de réunion"
    : has(t, /desk|seated|workstation|computer|laptop/) ? "bureau (meuble inclus)"
    : has(t, /board|screen|projector/) ? "tableau / écran"
    : "aucun décor, fond blanc";
  return `${people} · ${setting}`;
}
