import { createFileRoute } from "@tanstack/react-router";
import { LegalPage, renderSections, CONTACT_EMAIL, type Sections } from "@/components/legal-page";
import { useI18n } from "@/lib/i18n";

export const Route = createFileRoute("/terms")({
  head: () => ({ meta: [
    { title: "Terms of Use — Clario" },
    { name: "description", content: "The rules for using Clario: accounts, credits, subscriptions, refunds and acceptable use." },
    { property: "og:title", content: "Terms of Use — Clario" },
    { property: "og:description", content: "The rules for using Clario: accounts, credits, subscriptions and acceptable use." },
    { property: "og:type", content: "website" },
    { name: "twitter:card", content: "summary" },
  ] }),
  component: Terms,
});

const EN: Sections = [
  { h: "1. The service", p: "Clario is a study workspace: you import documents, annotate them in a notebook, ask an AI tutor questions and generate narrated explainer videos. By creating an account you accept these terms." },
  { h: "2. Your account", li: ["You must provide a valid email address and keep your password private.", "If you are under 13, a parent or guardian must agree to these terms.", "You are responsible for activity on your account."] },
  { h: "3. Your content", p: "Documents, notes and annotations remain yours. You grant Clario only the rights needed to store, display and process them to provide the service. Do not upload content you have no right to use." },
  { h: "4. Acceptable use", li: ["No illegal, hateful, sexual or violent content.", "No attempts to bypass limits, credits or security, or to automate requests.", "No use of Clario to cheat in graded exams where it is forbidden."] },
  { h: "5. AI answers", p: "Clario's answers and videos are generated by AI and may contain mistakes. Always check important information with your teacher or course materials." },
  { h: "6. Plans, credits and refunds", li: ["Purchased credits never expire; monthly usage caps may apply.", "Subscriptions renew automatically until cancelled from your profile.", "Payments are handled by our payment provider (merchant of record). Refund requests can be sent within 14 days of purchase if credits were not used."] },
  { h: "7. Termination", p: "You can delete your account at any time. We may suspend accounts that break these terms." },
  { h: "8. Liability", p: "Clario is provided “as is”. To the extent permitted by law, we are not liable for indirect damages or lost data." },
  { h: "9. Changes and contact", p: `We may update these terms and will notify you of important changes. Questions: ${CONTACT_EMAIL}.` },
];
const FR: Sections = [
  { h: "1. Le service", p: "Clario est un espace d'étude : tu importes tes documents, tu les annotes dans un cahier, tu poses des questions à un tuteur IA et tu génères des vidéos explicatives narrées. En créant un compte, tu acceptes ces conditions." },
  { h: "2. Ton compte", li: ["Tu dois fournir une adresse e-mail valide et garder ton mot de passe privé.", "Si tu as moins de 13 ans, un parent ou tuteur doit accepter ces conditions.", "Tu es responsable de l'activité sur ton compte."] },
  { h: "3. Ton contenu", p: "Tes documents, notes et annotations restent à toi. Tu accordes à Clario seulement les droits nécessaires pour les stocker, les afficher et les traiter afin de fournir le service. N'importe pas de contenu que tu n'as pas le droit d'utiliser." },
  { h: "4. Utilisation acceptable", li: ["Aucun contenu illégal, haineux, sexuel ou violent.", "Aucune tentative de contourner les limites, crédits ou la sécurité, ni d'automatiser les requêtes.", "Ne pas utiliser Clario pour tricher lors d'examens où c'est interdit."] },
  { h: "5. Réponses de l'IA", p: "Les réponses et vidéos de Clario sont générées par IA et peuvent contenir des erreurs. Vérifie toujours les informations importantes avec ton enseignant ou tes supports de cours." },
  { h: "6. Forfaits, crédits et remboursements", li: ["Les crédits achetés n'expirent jamais ; des plafonds mensuels d'utilisation peuvent s'appliquer.", "Les abonnements se renouvellent automatiquement jusqu'à leur annulation depuis ton profil.", "Les paiements sont gérés par notre prestataire de paiement (marchand officiel). Une demande de remboursement peut être faite dans les 14 jours si les crédits n'ont pas été utilisés."] },
  { h: "7. Résiliation", p: "Tu peux supprimer ton compte à tout moment. Nous pouvons suspendre les comptes qui enfreignent ces conditions." },
  { h: "8. Responsabilité", p: "Clario est fourni « tel quel ». Dans la limite permise par la loi, nous ne sommes pas responsables des dommages indirects ou des pertes de données." },
  { h: "9. Modifications et contact", p: `Nous pouvons mettre à jour ces conditions et te préviendrons des changements importants. Questions : ${CONTACT_EMAIL}.` },
];

function Terms() {
  const { locale } = useI18n();
  const fr = locale === "fr";
  return <LegalPage title={fr ? "Conditions d'utilisation" : "Terms of Use"} updated={fr ? "Dernière mise à jour : 2 octobre 2026" : "Last updated: October 2, 2026"}>{renderSections(fr ? FR : EN)}</LegalPage>;
}
